name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  flake-check:
    name: Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: authentik-nix-fpletz
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build flake outputs
        run: nix flake check --no-update-lock-file -v -L
